# Generated by Django 2.0.1 on 2018-02-09 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20180206_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav', models.NullBooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Category')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='profile',
            field=models.ManyToManyField(through='books.ProfileCategory', to='books.Profile'),
        ),
    ]
